# Generated by Django 5.2 on 2025-07-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('addr', models.CharField(blank=True, max_length=50, null=True)),
                ('cname', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
