# Generated by Django 5.2 on 2025-07-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfpro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
