# Generated by Django 5.2 on 2025-07-17 06:26

import drfpro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfpro', '0002_alter_employee_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(validators=[drfpro.models.validate_age]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[drfpro.models.validate_age]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eno',
            field=models.IntegerField(validators=[drfpro.models.validate_eno]),
        ),
    ]
