# Generated by Django 5.2 on 2025-07-17 10:33

import drfpro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfpro', '0003_alter_employee_age_alter_employee_ename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[drfpro.models.validate_ename]),
        ),
    ]
