# Generated by Django 5.2 on 2025-08-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfpro', '0004_alter_employee_ename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
